In [12]:
import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

In [37]:
df = pd.read_csv('seeds_dataset.csv')

In [38]:
df.head()

a      p       c     lk     wk     ac    lkg  type
0  15.26  14.84  0.8710  5.763  3.312  2.221  5.220     1
1  14.88  14.57  0.8811  5.554  3.333  1.018  4.956     1
2  14.29  14.09  0.9050  5.291  3.337  2.699  4.825     1
3  13.84  13.94  0.8955  5.324  3.379  2.259  4.805     1
4  16.14  14.99  0.9034  5.658  3.562  1.355  5.175     1

In [39]:
X = df.iloc[:,:7]
y = df['type']

In [40]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix



# Split the dataset into training and testing sets (adjust test_size and random_state as needed)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the logistic regression model
model = LogisticRegression()

# Fit the model on the training data
model.fit(X_train, y_train)

# Predict on the test data
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

# Print the evaluation metrics
print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{conf_matrix}')
print(f'Classification Report:\n{classification_rep}')


Accuracy: 0.9047619047619048
Confusion Matrix:
[[ 9  0  2]
 [ 0 14  0]
 [ 2  0 15]]
Classification Report:
              precision    recall  f1-score   support

           1       0.82      0.82      0.82        11
           2       1.00      1.00      1.00        14
           3       0.88      0.88      0.88        17

    accuracy                           0.90        42
   macro avg       0.90      0.90      0.90        42
weighted avg       0.90      0.90      0.90        42



/home/iqube/.local/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [41]:
from sklearn.neighbors import KNeighborsClassifier




# Initialize the KNN model (specify the number of neighbors, 'n_neighbors')
model = KNeighborsClassifier(n_neighbors=5)  # Example: using 5 neighbors

# Fit the model on the training data
model.fit(X_train, y_train)

# Predict on the test data
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

# Print the evaluation metrics
print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{conf_matrix}')
print(f'Classification Report:\n{classification_rep}')


Accuracy: 0.9285714285714286
Confusion Matrix:
[[ 9  0  2]
 [ 0 14  0]
 [ 1  0 16]]
Classification Report:
              precision    recall  f1-score   support

           1       0.90      0.82      0.86        11
           2       1.00      1.00      1.00        14
           3       0.89      0.94      0.91        17

    accuracy                           0.93        42
   macro avg       0.93      0.92      0.92        42
weighted avg       0.93      0.93      0.93        42



In [47]:

from sklearn.ensemble import RandomForestClassifier

lst = []


for i in range(1,1000):
    print(f"n_estimators = {i}")
    # Initialize the Random Forest Classifier
    model = RandomForestClassifier(n_estimators=i, random_state=42)  # Example: using 100 trees

    # Fit the model on the training data
    model.fit(X_train, y_train)

    # Predict on the test data
    y_pred = model.predict(X_test)

    # Evaluate the model
    accuracy = accuracy_score(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    classification_rep = classification_report(y_test, y_pred)
    lst.append(accuracy)

    # Print the evaluation metrics
    print(f'Accuracy: {accuracy}')
    print(f'Confusion Matrix:\n{conf_matrix}')
    print(f'Classification Report:\n{classification_rep}')


n_estimators = 1
Accuracy: 0.9523809523809523
Confusion Matrix:
[[10  0  1]
 [ 0 14  0]
 [ 1  0 16]]
Classification Report:
              precision    recall  f1-score   support

           1       0.91      0.91      0.91        11
           2       1.00      1.00      1.00        14
           3       0.94      0.94      0.94        17

    accuracy                           0.95        42
   macro avg       0.95      0.95      0.95        42
weighted avg       0.95      0.95      0.95        42

n_estimators = 2
Accuracy: 0.9047619047619048
Confusion Matrix:
[[10  0  1]
 [ 0 14  0]
 [ 3  0 14]]
Classification Report:
              precision    recall  f1-score   support

           1       0.77      0.91      0.83        11
           2       1.00      1.00      1.00        14
           3       0.93      0.82      0.87        17

    accuracy                           0.90        42
   macro avg       0.90      0.91      0.90        42
weighted avg       0.91      0.90      0.91  

KeyboardInterrupt: 

In [52]:
model = RandomForestClassifier(n_estimators=15, random_state=42)  # Example: using 100 trees

# Fit the model on the training data
model.fit(X_train, y_train)


y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)
lst.append(accuracy)

# Print the evaluation metrics
print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{conf_matrix}')
print(f'Classification Report:\n{classification_rep}')


Accuracy: 0.9285714285714286
Confusion Matrix:
[[ 9  0  2]
 [ 0 14  0]
 [ 1  0 16]]
Classification Report:
              precision    recall  f1-score   support

           1       0.90      0.82      0.86        11
           2       1.00      1.00      1.00        14
           3       0.89      0.94      0.91        17

    accuracy                           0.93        42
   macro avg       0.93      0.92      0.92        42
weighted avg       0.93      0.93      0.93        42



In [55]:
import pickle 
f = open("WheatClassifier.pickle",'wb')

In [56]:
pickle.dump(model,f)